export enum INTERCOM_EVENTS {
  GET_ISSUE = "GET_ISSUE",
  CREATE_ISSUE = "CREATE_ISSUE",
  UPDATE_ISSUE = "UPDATE_ISSUE",
  GET_ISSUES = "GET_ISSUES",
  CREATE_COMMENT = "CREATE_COMMENT",
  GET_COMMENTS = "GET_COMMENTS",
  UPLOAD_FILE = "UPLOAD_FILE",
}
